### ISSUE TITLE
Permission error when accessing file inside /usr/local/var

### ISSUE THREAD

**Issue by gaastonsr** [mixmaxhq/custody-probe#1]
I get the following error trying to run services inside a Debian box.

https://github.com/mixmaxhq/custody-probe/blob/8531c81dd86535fbb5f88293134958d35daa818d/src/index.js#L6

```
emailapps_1             | /home/node/srv/node_modules/mkdirp/index.js:90
emailapps_1             |                     throw err0;
emailapps_1             |                     ^
emailapps_1             |
emailapps_1             | Error: EACCES: permission denied, mkdir '/usr/local/var'
emailapps_1             |     at Object.fs.mkdirSync (fs.js:885:18)
emailapps_1             |     at sync (/home/node/srv/node_modules/mkdirp/index.js:71:13)
emailapps_1             |     at sync (/home/node/srv/node_modules/mkdirp/index.js:77:24)
emailapps_1             |     at Function.sync (/home/node/srv/node_modules/mkdirp/index.js:77:24)
emailapps_1             |     at initializeProbe (/home/node/srv/node_modules/custody-probe/src/index.js:21:10)
emailapps_1             |     at Object.<anonymous> (/home/node/srv/app.js:10:27)
emailapps_1             |     at Module._compile (module.js:635:30)
emailapps_1             |     at Object.Module._extensions..js (module.js:646:10)
emailapps_1             |     at Module.load (module.js:554:32)
emailapps_1             |     at tryModuleLoad (module.js:497:12)
emailapps_1             |     at Function.Module._load (module.js:489:3)
emailapps_1             |     at Function.Module.runMain (module.js:676:10)
emailapps_1             |     at startup (bootstrap_node.js:187:16)
emailapps_1             |     at bootstrap_node.js:608:3
```

**Comment by gaastonsr** [comment]
I consider this to be a problem with my user, which he should be able to write to `/usr/local`
